"""Voice profile — schema + persistence for the user's writing voice.

This is the moat. Without it, generated cover letters sound like every
other AI-written application. With it, they sound like the user.

Flow:
  1. The user shares a writing sample with Claude Code (a real cover
     letter draft, a journal entry, a blog post). 500+ words ideal.
  2. Claude analyses the sample **in-conversation** following
     ``skills/danapply/workflows/voice_capture.md`` and produces a
     voice-profile JSON payload.
  3. ``danapply voice set <payload.json>`` validates the payload against
     ``VoiceProfile`` and saves ``voice_profile.yaml`` (machine-readable,
     source of truth) plus ``voice_profile.md`` (human-readable).
  4. Claude reads the YAML whenever it writes a cover letter, so
     generated text matches the user's voice.

The YAML is the user's voice — they can hand-edit it whenever the
captured version misses something. No API key is involved anywhere.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Schema — the structured voice profile
# ---------------------------------------------------------------------------
class VoiceProfile(BaseModel):
    """How the user actually writes."""

    model_config = ConfigDict(extra="allow")  # tolerate user-added fields

    # Sentence shape
    avg_sentence_length_words: int = 18
    sentence_rhythm: str = "balanced"
    """one of: 'short and punchy', 'balanced', 'long and flowing'"""

    formality_register: str = "neutral"
    """one of: 'formal', 'neutral', 'warm-conversational'"""

    # Word choice
    vocabulary_preferences: list[str] = Field(default_factory=list)
    """Phrases the user reaches for — 5-15 items."""

    vocabulary_avoidances: list[str] = Field(default_factory=list)
    """Phrases the user doesn't use ('passionate about', 'reach out', etc.)."""

    characteristic_phrases: list[str] = Field(default_factory=list)
    """5-10 verbatim sentences from the sample — used as pattern anchors."""

    # Structure
    opening_style: str = "claim"
    """one of: 'anecdote', 'claim', 'question', 'observation', 'quote'"""

    closing_style: str = "warm-confident"
    """one of: 'formal', 'warm', 'confident', 'reflective', 'warm-confident'"""

    # Register baseline — the user's natural overclaiming threshold
    superlatives_per_100_words: float = 0.5
    """Lower = more Danish-mode by default. Useful as a sanity check on outputs."""

    intensifiers_per_100_words: float = 1.0

    # Free-text observations Claude flagged about the user's style
    notes: str = ""

    # Provenance
    extracted_at: str = Field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))
    sample_word_count: int = 0
    extraction_method: str = "templated"
    """'claude' when analysed by Claude in-conversation; 'templated' when
    manually seeded; legacy profiles may say 'llm' (same meaning as
    'claude' — extracted by a model)."""


# ---------------------------------------------------------------------------
# Persistence — yaml is source of truth; md is the human-readable companion
# ---------------------------------------------------------------------------
def save_voice_profile(
    profile: VoiceProfile,
    profile_dir: Path,
) -> tuple[Path, Path]:
    """Write both the YAML and the markdown companion. Returns paths."""
    profile_dir.mkdir(parents=True, exist_ok=True)
    yaml_path = profile_dir / "voice_profile.yaml"
    md_path = profile_dir / "voice_profile.md"

    yaml_path.write_text(
        yaml.safe_dump(profile.model_dump(), sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    md_path.write_text(_render_voice_md(profile), encoding="utf-8")

    return yaml_path, md_path


def load_voice_profile(profile_dir: Path) -> VoiceProfile | None:
    """Load the voice profile if present. Returns None if not yet captured."""
    yaml_path = profile_dir / "voice_profile.yaml"
    if not yaml_path.exists():
        return None
    try:
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
        return VoiceProfile.model_validate(data)
    except (yaml.YAMLError, ValueError):
        return None


def _render_voice_md(profile: VoiceProfile) -> str:
    """Human-readable summary the user can scan + edit ideas from."""
    parts = [
        "# Voice profile",
        "",
        "_Auto-generated by `danapply voice capture`. The structured source",
        "of truth is `voice_profile.yaml` alongside this file — edit that_",
        "_one to update your voice; this markdown is just for reading._",
        "",
        f"**Captured:** {profile.extracted_at}  ",
        f"**Sample size:** {profile.sample_word_count} words  ",
        f"**Extraction method:** {profile.extraction_method}",
        "",
        "## Shape",
        f"- Average sentence length: **{profile.avg_sentence_length_words} words**",
        f"- Rhythm: **{profile.sentence_rhythm}**",
        f"- Formality: **{profile.formality_register}**",
        f"- Opening style: **{profile.opening_style}**",
        f"- Closing style: **{profile.closing_style}**",
        "",
        "## Register baseline (Danish-mode reference)",
        f"- Superlatives per 100 words: **{profile.superlatives_per_100_words:.2f}**",
        f"- Intensifiers per 100 words: **{profile.intensifiers_per_100_words:.2f}**",
        "",
        "## Vocabulary you reach for",
    ]
    if profile.vocabulary_preferences:
        for v in profile.vocabulary_preferences:
            parts.append(f"- {v}")
    else:
        parts.append("_(none captured)_")

    parts.extend(["", "## Vocabulary you avoid"])
    if profile.vocabulary_avoidances:
        for v in profile.vocabulary_avoidances:
            parts.append(f"- {v}")
    else:
        parts.append("_(none captured)_")

    parts.extend(["", "## Characteristic phrases (verbatim quotes)"])
    if profile.characteristic_phrases:
        for q in profile.characteristic_phrases:
            parts.append(f"> {q}")
            parts.append("")
    else:
        parts.append("_(none captured)_")

    if profile.notes:
        parts.extend(["## Notes", "", profile.notes])

    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Payload validation — Claude analysed the sample; the engine validates
# ---------------------------------------------------------------------------
def voice_profile_from_payload(payload: dict) -> VoiceProfile:
    """Validate a Claude-supplied voice analysis into a ``VoiceProfile``.

    Claude Code analyses the writing sample in-conversation (see
    ``workflows/voice_capture.md`` for the analysis instructions and field
    semantics) and hands the engine a JSON payload. This validates it and
    stamps provenance.

    Raises ``ValueError`` with a readable message on a malformed payload —
    the CLI surfaces it so Claude can correct the JSON and retry.
    """
    if not isinstance(payload, dict):
        raise ValueError(f"Voice payload must be a JSON object, got {type(payload).__name__}.")
    try:
        return VoiceProfile.model_validate({
            **payload,
            "extracted_at": datetime.now().isoformat(timespec="seconds"),
            "extraction_method": "claude",
        })
    except Exception as exc:
        raise ValueError(f"Voice payload failed validation: {exc}") from exc
